### ISSUE TITLE
shared .env for development

### ISSUE THREAD

**Issue by mivinci** [halobase/halobase-hybrid#1]
For you guys to quickly get started diving in HaloBase, copy the content below and paste it into file `.env`. You have to first create this file after cloning the repo.

```toml
TOKEN_SECRET = "n7rgt1ngxfj44kgtw8s8"

SURREAL_URL = "http://162.14.73.95:23001"
SURREAL_NS = "halobase"
SURREAL_DB = "dev"
SURREAL_USER = "root"
SURREAL_PASS = "da2b4ebf5280"

S3_URL = "http://162.14.73.95:23002"
S3_REGION = "us-east-1"
S3_BUCKET = "cf4780ed-ebcf-4ba7-ad9a-84b05ac079a8"
S3_KEY_ID = "Aeb8y8meLtnp9WE3QaG5"
S3_KEY_SECRET = "jKt8XYK6NQ8w0iHZptWcULdDB4SAN3SVHVaB6OZO"

OPENAI_URL = ""
OPENAI_KEY = ""
```

Note that these variables are sensitive and may vary at any time, so **DO NOT** use them in any of your production environment. 

And please show mercy 🙏 各位手下留情（
